wip

diff --git a/.github/workflows/mrc-usage-report.yml b/.github/workflows/mrc-usage-report.yml
--- a/.github/workflows/mrc-usage-report.yml
+++ b/.github/workflows/mrc-usage-report.yml
@@ -153,18 +153,18 @@ jobs:
           chmod 777 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.html
           chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json
           chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.html
-          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json
-          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.html
+          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json
+          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.html
 
 
           echo "Checking for input files:"
           ls -la ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json || echo "mrc-maas-ops-ui-usage-report.json not found"
           ls -la ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json || echo "mrc-maas-ui-usage-report.json not found"
-          ls -la ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json || echo "mrc-broker-usage-report.json not found"
+          ls -la ../../../broker/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json || echo "mrc-broker-manager-usage-report.json not found"
           echo "Installing dependencies..."
           npm install 
           echo "Running npm start with parameters..."
-          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json -p3 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json -o merged-report.json -h merged-report.html
+          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json -p3 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json -o merged-report.json -h merged-report.html
 
           chmod 777 merged-report.json
           chmod 777 merged-report.html
