mrc

diff --git a/.github/workflows/mrc-usage-report.yml b/.github/workflows/mrc-usage-report.yml
--- a/.github/workflows/mrc-usage-report.yml
+++ b/.github/workflows/mrc-usage-report.yml
@@ -136,11 +136,11 @@ jobs:
           ls -la
           echo "Checking for input files:"
           ls -la ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json || echo "maas-ui-report.json not found"
-          ls -la ../../../maas-ui/mrc-maas-ui-report.json || echo "maas-ops-ui-report.json not found"
+          ls -la ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-report.json || echo "maas-ops-ui-report.json not found"
           echo "Installing dependencies..."
           npm install 
           echo "Running npm start with parameters..."
-          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/mrc-maas-ui-report.json -o merged-report.json -h merged-report.html
+          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-report.json -o merged-report.json -h merged-report.html
 
           echo "Contents of merged JSON report:"
           cat merged-report.json
