added broker manager

diff --git a/.github/workflows/mrc-usage-report.yml b/.github/workflows/mrc-usage-report.yml
--- a/.github/workflows/mrc-usage-report.yml
+++ b/.github/workflows/mrc-usage-report.yml
@@ -69,6 +69,14 @@ jobs:
           echo "maas-ops-ui-repo/tools/json-splitter location: $(pwd)/maas-ops-ui-repo/tools/json-splitter"
           ls -la maas-ops-ui-repo/tools/json-splitter || echo "json-splitter directory not found"
 
+      - name: Checkout broker
+        uses: actions/checkout@v4
+        with:
+          repository: SolaceDev/broker-manager
+          ref: mrc-usage-report
+          path: broker-manager-repo
+          token: ${{ secrets.PACKAGES_ADMIN_TOKEN }}
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
@@ -92,16 +100,6 @@ jobs:
 
           echo "Generating HTML report..."
           npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f html
-
-
-          # cd reports
-
-          # cat mrc-usage-report.html
-          # cat mrc-usage-report.json
-
-
-          # cat mrc-usage-report.html | wc -l
-          # cat mrc-usage-report.json | wc -l
 
         working-directory: maas-ui-repo/tools/mrc-usage-report
 
@@ -129,9 +127,24 @@ jobs:
 
         working-directory: maas-ops-ui-repo/tools/mrc-usage-report
 
-      - name: Step 3. Merge reports
+      - name: Step 3. Generate broker report
         run: |
-          echo "==== STEP 3: MERGE REPORTS ===="
+          echo "==== STEP 3: GENERATE BROKER REPORT ===="
+          echo "Current working directory: $(pwd)"
+          npm install
+          npm run build
+
+          echo "Generating JSON report..."
+          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f json 
+
+          echo "Generating HTML report..."
+          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f html
+
+        working-directory: broker-manager-repo/tools/mrc-usage-report
+
+      - name: Step 4. Merge reports
+        run: |
+          echo "==== STEP 4: MERGE REPORTS ===="
           echo "Current working directory: $(pwd)"
           ls -la
 
@@ -140,24 +153,27 @@ jobs:
           chmod 777 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.html
           chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json
           chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.html
+          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json
+          chmod 777 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.html
 
 
           echo "Checking for input files:"
           ls -la ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json || echo "mrc-maas-ops-ui-usage-report.json not found"
           ls -la ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json || echo "mrc-maas-ui-usage-report.json not found"
+          ls -la ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json || echo "mrc-broker-usage-report.json not found"
           echo "Installing dependencies..."
           npm install 
           echo "Running npm start with parameters..."
-          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json -o merged-report.json -h merged-report.html
+          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json -p3 ../../../broker/tools/mrc-usage-report/reports/mrc-broker-usage-report.json -o merged-report.json -h merged-report.html
 
           chmod 777 merged-report.json
           chmod 777 merged-report.html
 
         working-directory: maas-ops-ui-repo/tools/mrc-report-merger
 
-      - name: Step 4. Split merged JSON
+      - name: Step 5. Split merged JSON
         run: |
-          echo "==== STEP 4: SPLIT MERGED JSON ===="
+          echo "==== STEP 5: SPLIT MERGED JSON ===="
           echo "Current working directory: $(pwd)"
           echo "Working directory for this step: $(pwd)/maas-ops-ui-repo/tools/json-splitter"
           ls -la
@@ -177,15 +193,10 @@ jobs:
 
         working-directory: maas-ops-ui-repo/tools/json-splitter
 
-      - name: Step 5. Upload merged reports
+      - name: Step 6. Upload merged reports
         uses: actions/upload-artifact@v4
         with:
           name: merged-reports
           path: |
             maas-ops-ui-repo/tools/mrc-report-merger/merged-report.json
             maas-ops-ui-repo/tools/mrc-report-merger/merged-report.html
-
-      - name: Step 6. Deploy to GitHub Pages
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: maas-ops-ui-repo/tools/mrc-report-merger/merged-report.html # Path to the HTML report to be published
